name: Get MyShopping latest release version
on:
  schedule:
    - cron:  '0 6 * * *'
  workflow_dispatch:
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch release versions
        id: fetch_versions
        run: |
          echo "remote_version=$(curl -sL https://api.github.com/repos/sokolovromann/MyShopping/releases/latest | jq -r '.tag_name')" >>$GITHUB_OUTPUT
          echo "local_version=$(curl -sL https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest | jq -r '.tag_name')" >>$GITHUB_OUTPUT
      - name: Show versions
        env:
          remote_version: ${{ steps.fetch_versions.outputs.remote_version }}
          local_version: ${{ steps.fetch_versions.outputs.local_version }}
        run: echo "local version ($local_version) vs remote version ($remote_version)."
      - name: Create new version release
        env:
          remote_version: ${{ steps.fetch_versions.outputs.remote_version }}
          local_version: ${{ steps.fetch_versions.outputs.local_version }}
        if: env.remote_version != env.local_version
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: True
          tag: ${{ env.remote_version }}
          name: "Release build (${{ env.remote_version }})"
          omitBody: True
          token: ${{ secrets.GITHUB_TOKEN }}
