name: Get MyShopping latest release version
on:
  schedule:
    - cron:  '0 6 * * *'
  workflow_dispatch:
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch release versions
        id: fetch_versions
        run: |
          echo "remote_version=$(curl -sL https://api.github.com/repos/sokolovromann/MyShopping/releases/latest | jq -r '.tag_name')" >>$GITHUB_OUTPUT
          echo "local_version=$(curl -sL https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest | jq -r '.tag_name')" >>$GITHUB_OUTPUT
      - name: Show versions
        env:
          remote_version: ${{ steps.fetch_versions.outputs.remote_version }}
          local_version: ${{ steps.fetch_versions.outputs.local_version }}
        run: echo "local version ($local_version) vs remote version ($remote_version)."
      - name: Create new version tag
        env:
          remote_version: ${{ steps.fetch_versions.outputs.remote_version }}
          local_version: ${{ steps.fetch_versions.outputs.local_version }}
        if: ${{ remote_version != local_version }}
        run: echo "Creating new tag..."
        #uses: laputansoft/github-tag-action@v4.6
        #with:
        #  github_token: ${{ env.github-token }}
        #  tag: ${{ steps.package-version.outputs.version }}
